
CHIP_DIR = drivers/chip/stm32f10x

# SRC += $(CHIP_DIR)/STM32F10x_StdPeriph_Driver/src/misc.c
# SRC += $(CHIP_DIR)/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.c
# SRC += $(CHIP_DIR)/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.c
# SRC += $(CHIP_DIR)/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.c
# SRC += $(CHIP_DIR)/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.c
# SRC += $(CHIP_DIR)/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.c
# SRC += $(CHIP_DIR)/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.c
# SRC += $(CHIP_DIR)/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.c
# SRC += $(CHIP_DIR)/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.c
# SRC += $(CHIP_DIR)/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.c
# SRC += $(CHIP_DIR)/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.c
# SRC += $(CHIP_DIR)/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.c
# SRC += $(CHIP_DIR)/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.c
# SRC += $(CHIP_DIR)/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.c
# SRC += $(CHIP_DIR)/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.c
# SRC += $(CHIP_DIR)/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.c
# SRC += $(CHIP_DIR)/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.c
# SRC += $(CHIP_DIR)/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.c
# SRC += $(CHIP_DIR)/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.c
# SRC += $(CHIP_DIR)/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.c
# SRC += $(CHIP_DIR)/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.c
# SRC += $(CHIP_DIR)/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.c
# SRC += $(CHIP_DIR)/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.c
# CFLAGS += -I$(SDKPATH)/drivers/chip/stm32f10x/STM32F10x_StdPeriph_Driver/inc
# CFLAGS += -I$(SDKPATH)/drivers/CMSIS/Device/ST/STM32F10x

SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_adc.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_adc_ex.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_can.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_cec.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_cortex.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_crc.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_dac.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_dac_ex.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_dma.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_eth.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_exti.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_flash.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_flash_ex.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_gpio.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_gpio_ex.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_hcd.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_i2c.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_i2s.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_irda.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_iwdg.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_mmc.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_msp_template.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_nand.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_nor.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_pccard.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_pcd.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_pcd_ex.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_pwr.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_rcc.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_rcc_ex.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_rtc.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_rtc_ex.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_sd.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_smartcard.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_spi.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_sram.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_tim.c
# SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_timebase_rtc_alarm_template.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_timebase_tim_template.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_tim_ex.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_uart.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_usart.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_hal_wwdg.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_ll_adc.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_ll_crc.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_ll_dac.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_ll_dma.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_ll_exti.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_ll_fsmc.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_ll_gpio.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_ll_i2c.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_ll_pwr.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_ll_rcc.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_ll_rtc.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_ll_sdmmc.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_ll_spi.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_ll_tim.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_ll_usart.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_ll_usb.c
SRC += $(CHIP_DIR)/STM32F1xx_HAL_Driver/src/stm32f1xx_ll_utils.c

CFLAGS += -I$(SDKPATH)/drivers/chip/stm32f10x/STM32F1xx_HAL_Driver/inc
CFLAGS += -I$(SDKPATH)/drivers/CMSIS/Include
CFLAGS += -I$(SDKPATH)/drivers/CMSIS/Device/ST/STM32F1xx/Include

CFLAGS += -DSTM32F10X_MD
CFLAGS += -DUSE_STDPERIPH_DRIVER



