
CHIP_DIR = drivers/chip/stm32l5xx

SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_adc.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_adc_ex.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_comp.c
SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_cortex.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_crc.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_crc_ex.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_cryp.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_cryp_ex.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_dac.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_dac_ex.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_dfsdm.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_dfsdm_ex.c
SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_dma.c
SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_dma_ex.c
SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_exti.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_fdcan.c
SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_flash.c
SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_flash_ex.c
SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_flash_ramfunc.c
SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_gpio.c
SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_gtzc.c
SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_hash.c
SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_hash_ex.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_i2c.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_i2c_ex.c
SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_icache.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_irda.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_iwdg.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_lptim.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_mmc.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_mmc_ex.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_msp_template.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_nand.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_nor.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_opamp.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_opamp_ex.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_ospi.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_otfdec.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_pcd.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_pcd_ex.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_pka.c
SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_pwr.c
SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_pwr_ex.c
SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_rcc.c
SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_rcc_ex.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_rng.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_rng_ex.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_rtc.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_rtc_ex.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_sai.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_sai_ex.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_sd.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_sd_ex.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_smartcard.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_smartcard_ex.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_smbus.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_smbus_ex.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_spi.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_spi_ex.c
SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_sram.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_tim.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_tim_ex.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_tsc.c
SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_uart.c
SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_uart_ex.c
SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_usart.c
SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_usart_ex.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_hal_wwdg.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_ll_adc.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_ll_comp.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_ll_crc.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_ll_crs.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_ll_dac.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_ll_dma.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_ll_exti.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_ll_fmc.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_ll_gpio.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_ll_i2c.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_ll_icache.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_ll_lptim.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_ll_lpuart.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_ll_opamp.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_ll_pka.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_ll_pwr.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_ll_rcc.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_ll_rng.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_ll_rtc.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_ll_sdmmc.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_ll_spi.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_ll_tim.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_ll_ucpd.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_ll_usart.c
# SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_ll_usb.c
SRC += $(CHIP_DIR)/STM32L5xx_HAL_Driver/src/stm32l5xx_ll_utils.c

SRC += $(CHIP_DIR)/BSP/STM32L5xx_Nucleo/stm32l5xx_nucleo.c
SRC += $(CHIP_DIR)/BSP/STM32L5xx_Nucleo/stm32l5xx_nucleo_usbpd_pwr.c

CFLAGS += -I$(SDKPATH)/drivers/chip/stm32l5xx/STM32L5xx_HAL_Driver/inc
CFLAGS += -I$(SDKPATH)/drivers/chip/stm32l5xx/BSP/STM32L5xx_Nucleo
CFLAGS += -I$(SDKPATH)/drivers/CMSIS/Include
CFLAGS += -DHAL_DRIVER_ENABLE
